version: "3.6"

services:
  backend:
    image: zawadzkib/recruitment_backend:0.2.1
    ports:
      - 8081:8081

  frontend:
    image: zawadzkib/recruitment_frontend:0.2.1
    environment:
      - env=docker
    ports:
      - 80:8080
